[package]
name = "ip-resolver-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
argh = "0.1.7"
thiserror = "1.0.31"
tokio = { version = "1", features = ["net", "time", "rt-multi-thread", "macros"] }

ip-resolver = { path = "../ip-resolver" }
